In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('Datasets/play_tennis.csv')

In [4]:
data

    day   outlook  temp humidity    wind play
0    D1     Sunny   Hot     High    Weak   No
1    D2     Sunny   Hot     High  Strong   No
2    D3  Overcast   Hot     High    Weak  Yes
3    D4      Rain  Mild     High    Weak  Yes
4    D5      Rain  Cool   Normal    Weak  Yes
5    D6      Rain  Cool   Normal  Strong   No
6    D7  Overcast  Cool   Normal  Strong  Yes
7    D8     Sunny  Mild     High    Weak   No
8    D9     Sunny  Cool   Normal    Weak  Yes
9   D10      Rain  Mild   Normal    Weak  Yes
10  D11     Sunny  Mild   Normal  Strong  Yes
11  D12  Overcast  Mild     High  Strong  Yes
12  D13  Overcast   Hot   Normal    Weak  Yes
13  D14      Rain  Mild     High  Strong   No

In [7]:
(3/5)*(2/5)*(4/5)*(2/5)*(5/14)

0.02742857142857143

In [9]:
data['play'].value_counts()
#P(Yes)
py = 9/14
#P(No)
pn = 5/14

In [10]:
py, pn

(0.6428571428571429, 0.35714285714285715)

In [12]:
#Outlook
pd.crosstab(data['outlook'], data['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [13]:
pon = 0
prn = 2/5
psn = 3/5

poy=4/9
pry=3/9
psy=2/9

In [14]:
pd.crosstab(data['temp'], data['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [15]:
p_cool_no = 1/5
p_hot_no = 2/5
p_mild_no = 2/5

p_cool_y = 3/9
p_hot_y = 2/9
p_mild_y = 4/9

In [16]:
pd.crosstab(data['humidity'], data['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [17]:
p_high_no = 4/5
p_normal_no = 1/5

p_high_y = 3/9
p_normal_y = 6/9

In [18]:
pd.crosstab(data['wind'], data['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [19]:
p_strong_no = 3/5
p_weak_no = 2/5

p_strong_y = 3/9
p_weak_y = 6/9

In [20]:
#Outlook=sunny, temp=hot, humidity=high, wind=weak

p_yes = py*psy*p_hot_y*p_high_y*p_weak_y

In [21]:
p_no = pn*psn*p_hot_no*p_high_no*p_weak_no

In [22]:
p_yes, p_no

(0.007054673721340388, 0.02742857142857143)

In [23]:
# No play